/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        brandingerror: "var(--brandingerror)",
        brandingsuccess: "var(--brandingsuccess)",
        "brandingsuccess-bright": "var(--brandingsuccess-bright)",
        "brandingsuccess-dark": "var(--brandingsuccess-dark)",
        brandingwarning: "var(--brandingwarning)",
  "gray-scalegray-100": "var(--gray-scalegray-100)",
  "gray-scalegray-200": "var(--gray-scalegray-200)",
  "gray-scalegray-300": "var(--gray-scalegray-300)",
  "gray-scalegray-400": "var(--gray-scalegray-400)",
  "gray-scalegray-50": "var(--gray-scalegray-50)",
  "gray-scalegray-500": "var(--gray-scalegray-500)",
  "gray-scalegray-600": "var(--gray-scalegray-600)",
  "gray-scalegray-700": "var(--gray-scalegray-700)",
  "gray-scalegray-800": "var(--gray-scalegray-800)",
  "gray-scalegray-900": "var(--gray-scalegray-900)",
  "gray-scalewhite": "var(--gray-scalewhite)",
  "gren-gray-scale100": "var(--gren-gray-scale100)",
  "gren-gray-scale200": "var(--gren-gray-scale200)",
  "gren-gray-scale300": "var(--gren-gray-scale300)",
  "gren-gray-scale400": "var(--gren-gray-scale400)",
  "gren-gray-scale50": "var(--gren-gray-scale50)",
  "gren-gray-scale500": "var(--gren-gray-scale500)",
  "gren-gray-scale600": "var(--gren-gray-scale600)",
  "gren-gray-scale700": "var(--gren-gray-scale700)",
  "gren-gray-scale800": "var(--gren-gray-scale800)",
  "gren-gray-scale900": "var(--gren-gray-scale900)",
},
      fontFamily: {
        "body-large-body-large-400": "var(--body-large-body-large-400-font-family)",
        "body-large-body-large-500": "var(--body-large-body-large-500-font-family)",
        "body-large-body-large-600": "var(--body-large-body-large-600-font-family)",
        "body-medium-body-medium-400": "var(--body-medium-body-medium-400-font-family)",
        "body-medium-body-medium-500": "var(--body-medium-body-medium-500-font-family)",
        "body-medium-body-medium-600": "var(--body-medium-body-medium-600-font-family)",
        "body-small-body-small-400": "var(--body-small-body-small-400-font-family)",
        "body-small-body-small-500": "var(--body-small-body-small-500-font-family)",
        "body-small-body-small-600": "var(--body-small-body-small-600-font-family)",
        "body-tiny-body-tiny-400": "var(--body-tiny-body-tiny-400-font-family)",
        "body-tiny-body-tiny-500": "var(--body-tiny-body-tiny-500-font-family)",
        "body-tiny-body-tiny-600": "var(--body-tiny-body-tiny-600-font-family)",
        "body-XL-body-XL-400": "var(--body-XL-body-XL-400-font-family)",
        "body-XL-body-XL-500": "var(--body-XL-body-XL-500-font-family)",
        "body-XL-body-XL-600": "var(--body-XL-body-XL-600-font-family)",
        "body-XXL-body-XXL-400": "var(--body-XXL-body-XXL-400-font-family)",
        "body-XXL-body-XXL-500": "var(--body-XXL-body-XXL-500-font-family)",
        "body-XXL-body-XXL-600": "var(--body-XXL-body-XXL-600-font-family)",
        "CAPS-LOCK-large-caps-lock": "var(--CAPS-LOCK-large-caps-lock-font-family)",
        "CAPS-LOCK-medium-caps-lock": "var(--CAPS-LOCK-medium-caps-lock-font-family)",
        "CAPS-LOCK-small-caps-lock": "var(--CAPS-LOCK-small-caps-lock-font-family)",
        "CAPS-LOCK-tiny-caps-lock": "var(--CAPS-LOCK-tiny-caps-lock-font-family)",
        "CAPS-LOCK-xtra-large-caps-lock": "var(--CAPS-LOCK-xtra-large-caps-lock-font-family)",
        "CAPS-LOCK-XXL-caps-lock": "var(--CAPS-LOCK-XXL-caps-lock-font-family)",
        "display-01-display-01-400": "var(--display-01-display-01-400-font-family)",
        "display-01-display-01-600": "var(--display-01-display-01-600-font-family)",
        "heading-01-heading-01-400": "var(--heading-01-heading-01-400-font-family)",
        "heading-01-heading-01-600": "var(--heading-01-heading-01-600-font-family)",
        "heading-02-heading-02-400": "var(--heading-02-heading-02-400-font-family)",
        "heading-02-heading-02-600": "var(--heading-02-heading-02-600-font-family)",
        "heading-03-heading-03-400": "var(--heading-03-heading-03-400-font-family)",
        "heading-03-heading-03-600": "var(--heading-03-heading-03-600-font-family)",
        "heading-04-heading-04-400": "var(--heading-04-heading-04-400-font-family)",
        "heading-05-heading-05-400": "var(--heading-05-heading-05-400-font-family)",
        "heading-05-heading-05-600": "var(--heading-05-heading-05-600-font-family)",
      },
      
      boxShadow: {
        "blog-shadow": "var(--blog-shadow)",
        featured: "var(--featured)",
        "hover-shadow": "var(--hover-shadow)",
        "leaf-blur": "var(--leaf-blur)",
        "line-shadow": "var(--line-shadow)",
        // ... other boxShadow definitions
      },
    },
  },
  plugins: [],
};
